name: Run the Standalone64 build
on:
  workflow_dispatch: {}
jobs:
  build:
    name: Run the Standalone64 build
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v2 を利用して作業ディレクトリに
      # Unity プロジェクトの中身をダウンロードしてくる
      - name: Check out my unity project.
        uses: actions/checkout@v2

      # GameCI の Builder を利用して、
      # Unity プロジェクトのビルドを実行する
      - name: Run the Standalone64 build
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          # 今回は Standalone64 ビルドを行いたいため Standalone64 を指定する
          # WebGL 以外の指定可能な値は下記に記載の値が利用可能
          # ref: https://docs.unity3d.com/ScriptReference/BuildTarget.html
          targetPlatform: StandaloneWindows64  
          unityVersion: 2021.3.2f1

      # Builder で出力した Standalone64 ビルドをアーティファクトでダウンロード可能にする
      - name: Upload the Standalone64 Build
        uses: actions/upload-artifact@v2
        with:
          name: Standalone64 Build
          path: build